language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator_hexe_ruby_amqp' ]; then cd .. && eval "mv $currentfolder generator_hexe_ruby_amqp" && cd generator_hexe_ruby_amqp; fi
